CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_app_user_username ON app_user (username);

CREATE TABLE IF NOT EXISTS location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description TEXT,
    longitude DOUBLE PRECISION NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    cover_photo_id BIGINT,
    travel_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_location_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

ALTER TABLE location ADD COLUMN IF NOT EXISTS user_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_location_deleted ON location (deleted);
CREATE INDEX IF NOT EXISTS idx_location_user_deleted ON location (user_id, deleted);

CREATE TABLE IF NOT EXISTS photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    cos_key VARCHAR(512) NOT NULL,
    url VARCHAR(1024) NOT NULL,
    thumb_url VARCHAR(1024),
    width INT,
    height INT,
    orientation VARCHAR(16),
    file_size BIGINT,
    shot_date DATE,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    review_reason TEXT,
    reviewed_at TIMESTAMP,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_photo_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_photo_location FOREIGN KEY (location_id) REFERENCES location(id)
);

ALTER TABLE photo ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE photo ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'pending';
ALTER TABLE photo ADD COLUMN IF NOT EXISTS review_reason TEXT;
ALTER TABLE photo ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_photo_location ON photo (location_id);
CREATE INDEX IF NOT EXISTS idx_photo_deleted ON photo (deleted);
CREATE INDEX IF NOT EXISTS idx_photo_user_deleted ON photo (user_id, deleted);
CREATE INDEX IF NOT EXISTS idx_photo_user_status ON photo (user_id, status);

CREATE TABLE IF NOT EXISTS photo_embedding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    photo_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    caption TEXT,
    tags TEXT,
    search_text TEXT,
    embedding CLOB,
    index_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    analysis_model VARCHAR(128),
    embedding_model VARCHAR(128),
    retry_count INT NOT NULL DEFAULT 0,
    index_error TEXT,
    content_hash VARCHAR(64),
    indexed_at TIMESTAMP,
    next_retry_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_embedding_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_photo_embedding_photo FOREIGN KEY (photo_id) REFERENCES photo(id),
    CONSTRAINT fk_photo_embedding_location FOREIGN KEY (location_id) REFERENCES location(id)
);

-- H2 is also used with a persistent local file. CREATE TABLE IF NOT EXISTS does
-- not add new columns to databases created by an older application version, so
-- keep these additive upgrades here as well as in the PostgreSQL Flyway script.
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS embedding CLOB;
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS index_status VARCHAR(16) DEFAULT 'PENDING' NOT NULL;
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS analysis_model VARCHAR(128);
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS embedding_model VARCHAR(128);
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS retry_count INT DEFAULT 0 NOT NULL;
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS index_error TEXT;
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS content_hash VARCHAR(64);
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS indexed_at TIMESTAMP;
ALTER TABLE photo_embedding ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_photo_embedding_user ON photo_embedding (user_id);
CREATE INDEX IF NOT EXISTS idx_photo_embedding_photo ON photo_embedding (photo_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_photo_embedding_photo ON photo_embedding (photo_id);
CREATE INDEX IF NOT EXISTS idx_photo_embedding_status ON photo_embedding (user_id, index_status);

CREATE TABLE IF NOT EXISTS blog_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_blog_category_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uk_blog_category_user_slug UNIQUE (user_id, slug)
);

CREATE TABLE IF NOT EXISTS blog_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(32) NOT NULL,
    slug VARCHAR(48) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_blog_tag_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uk_blog_tag_user_slug UNIQUE (user_id, slug)
);

CREATE TABLE IF NOT EXISTS blog_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    original_name VARCHAR(255),
    content_type VARCHAR(128),
    width INT,
    height INT,
    fallback_url VARCHAR(1024),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_blog_asset_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uk_blog_asset_object_key UNIQUE (object_key)
);

CREATE TABLE IF NOT EXISTS blog_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT,
    cover_asset_id BIGINT,
    title VARCHAR(160) NOT NULL DEFAULT '',
    slug VARCHAR(180) NOT NULL,
    excerpt VARCHAR(320),
    content_markdown CLOB NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_blog_post_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_blog_post_category FOREIGN KEY (category_id) REFERENCES blog_category(id),
    CONSTRAINT fk_blog_post_cover FOREIGN KEY (cover_asset_id) REFERENCES blog_asset(id),
    CONSTRAINT uk_blog_post_user_slug UNIQUE (user_id, slug),
    CONSTRAINT ck_blog_post_status CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

CREATE TABLE IF NOT EXISTS blog_post_tag (
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_blog_post_tag PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_blog_post_tag_post FOREIGN KEY (post_id) REFERENCES blog_post(id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_post_tag_tag FOREIGN KEY (tag_id) REFERENCES blog_tag(id)
);

CREATE INDEX IF NOT EXISTS idx_blog_post_public ON blog_post (user_id, status, published_at);
CREATE INDEX IF NOT EXISTS idx_blog_post_category ON blog_post (category_id, status, published_at);
CREATE INDEX IF NOT EXISTS idx_blog_asset_user_deleted ON blog_asset (user_id, deleted);
CREATE INDEX IF NOT EXISTS idx_blog_post_tag_tag ON blog_post_tag (tag_id, post_id);
