CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_app_user_username ON app_user (username);

CREATE TABLE IF NOT EXISTS location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description TEXT,
    longitude DOUBLE PRECISION NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    cover_photo_id BIGINT,
    travel_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_location_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

ALTER TABLE location ADD COLUMN IF NOT EXISTS user_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_location_deleted ON location (deleted);
CREATE INDEX IF NOT EXISTS idx_location_user_deleted ON location (user_id, deleted);

CREATE TABLE IF NOT EXISTS photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    cos_key VARCHAR(512) NOT NULL,
    url VARCHAR(1024) NOT NULL,
    thumb_url VARCHAR(1024),
    width INT,
    height INT,
    orientation VARCHAR(16),
    file_size BIGINT,
    shot_date DATE,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    review_reason TEXT,
    reviewed_at TIMESTAMP,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_photo_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_photo_location FOREIGN KEY (location_id) REFERENCES location(id)
);

ALTER TABLE photo ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE photo ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'pending';
ALTER TABLE photo ADD COLUMN IF NOT EXISTS review_reason TEXT;
ALTER TABLE photo ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_photo_location ON photo (location_id);
CREATE INDEX IF NOT EXISTS idx_photo_deleted ON photo (deleted);
CREATE INDEX IF NOT EXISTS idx_photo_user_deleted ON photo (user_id, deleted);
CREATE INDEX IF NOT EXISTS idx_photo_user_status ON photo (user_id, status);

CREATE TABLE IF NOT EXISTS photo_embedding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    photo_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    caption TEXT,
    tags TEXT,
    search_text TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_embedding_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_photo_embedding_photo FOREIGN KEY (photo_id) REFERENCES photo(id),
    CONSTRAINT fk_photo_embedding_location FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE INDEX IF NOT EXISTS idx_photo_embedding_user ON photo_embedding (user_id);
CREATE INDEX IF NOT EXISTS idx_photo_embedding_photo ON photo_embedding (photo_id);
